### PR TITLE
Frontend/feature/poll tag

### PR DESCRIPTION
**Pull request by selinisik**

### CODE REVIEW

**Comment by AliNasra** [comment]
I am creating this poll
image
This modal appears on the screen
image
When I click on the Find Available Categories button, a message appears "No available tags found". Whatever, I typed politics in the input box.
image
When I fetched the poll in my feed, I found no tags.
image

**Comment by AliNasra** [comment]
I figured out that I approached this functionality incorrectly: a user learning in action
I open a new poll!
image
The modal appears!
image
I should type in a text for recommendations to roll in. Here they come! I choose labor union and worker tags
image
But the tags didn't appear, yet!
image

**Comment by AliNasra** [comment]
A new trial
image
image
Still no tags
image

**Comment by AliNasra** [comment]
If I missing something out, please enlighten me @selinisik !

**Comment by selinisik** [comment]
> If I missing something out, please enlighten me @selinisik !

These tags will be used in search bar . They are not the same as poll tags.

**Comment by AliNasra** [comment]
> > If I missing something out, please enlighten me @selinisik !
> 
> These tags will be used in search bar . They are not the same as poll tags.

Understood. Good to Go!

**Review by AliNasra — APPROVED** [review]

**Pull request merged**
