### PR TITLE
Annotation UI

### PR DESCRIPTION
**Pull request by AliNasra**
The updated Implementation of the Annotation UI
Sample: View Annotation -> Click on Maverics from the annotations list:
image

### CODE REVIEW

**Comment by AliNasra** [comment]
This is the final implementation. A user can now:
1- See his/her own annotations
2- See All the annotations
3- Hide the annotations all together!
image

**Comment by AliNasra** [comment]
The backend has been integrated successfully, too!

**Review by enfurars — APPROVED** [review]
The UI looks nice and compatible with the subjects we learned. Well done Ali!

**Comment by AliNasra** [comment]
Thanks for your review, Enes!
I have updated the code such that the annotation list is retrieved given that the response is an object with an "annotations" feature.

**Pull request merged**
