### PR TITLE
Implementation of Sign-Up Design

### PR DESCRIPTION
**Pull request by enfurars**
I have added the input form with e-mail, username, password and birthday information. Also buttons to sign up with the form and Google is added. The main image is also added both to page and public file as it is in our mock up. Finally checkbox for platform terms is added. I have followed the design we made in our mock-up and added some comments where I thought necessary.

### CODE REVIEW

**Comment by YigitSekerci** [comment]
prediction-polls/frontend/package-lock.json What is this file? There are 19k lines in it, is it suppose to look like this? (I have no idea, I just want to know)

**Comment by enfurars** [comment]
> prediction-polls/frontend/package-lock.json What is this file? There are 19k lines in it, is it suppose to look like this? (I have no idea, I just want to know) @enfurars

Actually it was there when I cloned to my local. I ran npm install and npm start on my local then a version update occurred on that file and there was only 1 line changed. I thought it was one of the initialization files for frontend. @kutaysaran do you know the answer?

**Comment by kutaysaran** [comment]
It is used to guarantee that the project maintains consistent dependencies, no matter who installs it or where it's installed.

**Comment by YigitSekerci** [comment]
> It is used to guarantee that the project maintains consistent dependencies, no matter who installs it or where it's installed.

Got it, thx for info.

**Review by kutaysaran — APPROVED** [review]
It seems good.

**Pull request merged**
