### PR TITLE
Frontend/feature/moderation-not-moderator-jury-backend-connections

### PR DESCRIPTION
**Pull request by enfurars**
Tag selection on moderation-not-jury page is connected with backend with 2 API requests (moderators/my-tags) GET and POST. GET request is executed at every render of the page and POST request is executed every change on tag list. If a user selects more than 5 tags or selects no tags, no request is sent and warning message is shown. The information of member being moderator or not is also taken from backend using profile/myProfile endpoint and necessary page is shown accordingly. On the moderation-not-moderator page when a member clicks apply button a POST request is sent to /moderators/request-promotion end point and a success message to user is shown. Necessary CSS updates of new components are also done. Also I am rendering the posts with another GET request to endpoint /moderators/my-requests after a change occurs on the tags. I have also tested manually these new features as possible as I can.

### CODE REVIEW

**Comment by AliNasra** [comment]
The backend integration seems off somehow. For instance, when I click on the Sports tag, I get the question "When will Microsoft acquire OpenAI" whose only tag is technology, though I didn't pick it from among the choices. With the current selections, I thought I would be getting polls with tags related to politics and sports. Correct me if I am missing something please, Enes!
image

**Comment by enfurars** [comment]
> The backend integration seems off somehow. For instance, when I click on the Sports tag, I get the question "When will Microsoft acquire OpenAI" whose only tag is technology, though I didn't pick it from among the choices. With the current selections, I thought I would be getting polls with tags related to politics and sports. Correct me if I am missing something please, Enes! image

Yes, it expected to be so because the backend sends the same data no matter what for now. We have tested it with @EmreBatuhan manually. As I mentioned in the PR explanation I am re-rendering the posts after a change occurs on the tags. It will work as intended when backend updates the response. New tests will be made then. If any new problem arises we will be fixing it.

**Comment by AliNasra** [comment]
If that's the case, I think the UI is ready to go thought I recommend we merge this branch when the backend is fixed!

**Review by AliNasra — APPROVED** [review]

**Comment by AliNasra** [comment]
I have contacted @EmreBatuhan. We agreed that the UI can be merged for now and it shall be followed by a potential bug fix PR.

**Pull request merged**
